name: Upload NFT Metadata to IPFS

on:
  repository_dispatch:
    types: [upload-to-ipfs]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Lighthouse CLI
        run: npm install -g lighthouse-web3

      - name: Decode metadata JSON
        run: |
          echo "${{ github.event.client_payload.data }}" | base64 -d > metadata.json

      - name: Debug decoded JSON
        run: |
          file metadata.json
          cat metadata.json

      - name: Check Lighthouse CLI Version
        run: lighthouse-web3 --version

      - name: Upload metadata to IPFS (Lighthouse)
        id: upload
        run: |
          set -e
          if [[ ! -s metadata.json ]]; then
            echo "Error: metadata.json is missing or empty"
            exit 1
          fi
          # Try to upload and capture the full output for debugging
          UPLOAD_OUTPUT=$(lighthouse-web3 upload metadata.json --apiKey "${{ secrets.LIGHTHOUSE_API_KEY }}" 2>&1)
          echo "$UPLOAD_OUTPUT"
          CID=$(echo "$UPLOAD_OUTPUT" | grep -oE 'Qm[1-9A-HJ-NP-Za-km-z]{44,}' || echo "Upload failed")
          if [[ "$CID" == "Upload failed" || -z "$CID" ]]; then
            echo "Error: Failed to upload metadata to IPFS"
            exit 1
          fi
          echo "cid=${CID}" >> $GITHUB_OUTPUT

      - name: Write status file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin main
          mkdir -p status
          echo "{
            \"status\": \"done\",
            \"cid\": \"${{ steps.upload.outputs.cid }}\",
            \"timestamp\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"
          }" > status/${{ github.event.client_payload.id }}.json
          git add status/${{ github.event.client_payload.id }}.json
          git commit -m "Add status for ${{ github.event.client_payload.id }}"
          git push origin main
