name: Upload to IPFS

on:
  repository_dispatch:
    types: [upload-to-ipfs]

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Lighthouse CLI
        run: npm install -g lighthouse-web3

      - name: Decode image
        run: echo "${{ github.event.client_payload.data }}" | base64 -d > image.png

      - name: Upload to IPFS (Lighthouse)
        id: upload
        run: |
          CID=$(lighthouse-web3 upload image.png --apiKey "${{ secrets.LIGHTHOUSE_API_KEY }}" | grep -oE 'Qm[1-9A-HJ-NP-Za-km-z]{44,}')
          echo "cid=${CID}" >> $GITHUB_OUTPUT

      - name: Write status file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin main
          mkdir -p status
          echo "{
            \"status\": \"done\",
            \"cid\": \"${{ steps.upload.outputs.cid }}\",
            \"timestamp\": \"$(date -u +'%Y-%m-%dT%H:%M:%SZ')\"
          }" > status/${{ github.event.client_payload.id }}.json
          git add status/${{ github.event.client_payload.id }}.json
          git commit -m "Add status for ${{ github.event.client_payload.id }}"
          git push origin main
